# Generated by Django 6.0.3 on 2026-03-11 09:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_car_trip_delete_clubinfo_remove_equipment_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('bonus', 'Бонусы')], max_length=20, verbose_name='Способ оплаты')),
                ('transaction_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='ID транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %')),
                ('min_trip_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. стоимость поездки')),
                ('valid_from', models.DateTimeField(verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(verbose_name='Действует до')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Макс. использований')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Текущ. использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('driver_license', models.CharField(max_length=20, unique=True, verbose_name='Вод. удостоверение')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('total_trips', models.IntegerField(default=0, verbose_name='Всего поездок')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего потрачено')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-is_available', 'brand', 'model'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_time'], 'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Toyota', max_length=50, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], default='gasoline', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='car',
            name='last_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последнее ТО'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, help_text='км', verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот')], default='automatic', max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='км', null=True, verbose_name='Пройденное расстояние'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта окончания'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота окончания'),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumed',
            field=models.FloatField(blank=True, help_text='л', null=True, verbose_name='Потрачено топлива'),
        ),
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка поездки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта начала'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота начала'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('premium', 'Премиум')], db_index=True, default='economy', max_length=20, verbose_name='Класс авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_level',
            field=models.IntegerField(default=100, help_text='Проценты', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[А-Я]{1}\\d{3}[А-Я]{2}\\d{2,3}$', 'Введите корректный госномер')], verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_minute',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Цена за минуту'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='project.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_available', 'car_class'], name='project_car_is_avai_eead19_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['latitude', 'longitude'], name='project_car_latitud_b05d21_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_active', 'status'], name='project_tri_is_acti_a2ba04_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['car', '-start_time'], name='project_tri_car_id_6c69f8_idx'),
        ),
        migrations.AddField(
            model_name='carreview',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project.car'),
        ),
        migrations.AddField(
            model_name='carreview',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='project.trip'),
        ),
        migrations.AddField(
            model_name='payment',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='project.trip'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.userprofile'),
        ),
        migrations.AddField(
            model_name='carreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='carreview',
            unique_together={('user', 'trip')},
        ),
    ]
